-- GXPAY POS - sample catalog seed data (100 items)
-- Run this in your Supabase project's SQL Editor AFTER db/schema.sql has
-- already been run (this inserts into the catalog_items table it creates).
-- A realistic, varied mix of sale items and services for testing/demo
-- purposes - edit freely, or delete rows you don't want before running.
--
-- Once inserted, these appear automatically on both the Items tab and the
-- Checkout tab's item picker - both already read from GET /api/catalog,
-- which reads from this same table when Supabase is configured (see
-- store/catalogStore.js). No other setup or script needed beyond running
-- this once.

insert into catalog_items (name, price, type, currency) values
  ('Videography (full event)', 200000, 'service', 'NGN'),
  ('Electrician callout fee', 5000, 'service', 'NGN'),
  ('Makeup and gele service', 20000, 'service', 'NGN'),
  ('Catering service (per 50 guests)', 250000, 'service', 'NGN'),
  ('Private tutoring (per hour)', 5000, 'service', 'NGN'),
  ('Painting service (per room)', 20000, 'service', 'NGN'),
  ('Bluetooth earbuds', 15000, 'sale', 'NGN'),
  ('LED bulb (9W)', 1200, 'sale', 'NGN'),
  ('USB flash drive (32GB)', 4500, 'sale', 'NGN'),
  ('Sugar (1kg)', 1200, 'sale', 'NGN'),
  ('Event decoration (large hall)', 350000, 'service', 'NGN'),
  ('Tyre change (per tyre)', 2500, 'service', 'NGN'),
  ('Salt (500g)', 350, 'sale', 'NGN'),
  ('Milk powder (400g tin)', 2900, 'sale', 'NGN'),
  ('Alteration service', 3500, 'service', 'NGN'),
  ('Swimming pool session', 4000, 'service', 'NGN'),
  ('Website design service', 150000, 'service', 'NGN'),
  ('Earphones (wired)', 2500, 'sale', 'NGN'),
  ('Tailoring (native attire)', 15000, 'service', 'NGN'),
  ('Photography (full event)', 150000, 'service', 'NGN'),
  ('Notebook (A5, 100 pages)', 800, 'sale', 'NGN'),
  ('Yoga class', 5000, 'service', 'NGN'),
  ('Firewood (bundle)', 2000, 'sale', 'NGN'),
  ('AA batteries (pack of 4)', 900, 'sale', 'NGN'),
  ('Sound system rental (per day)', 45000, 'service', 'NGN'),
  ('Sunglasses', 4500, 'sale', 'NGN'),
  ('Car engine diagnostics', 12000, 'service', 'NGN'),
  ('Wristwatch', 12500, 'sale', 'NGN'),
  ('Manicure', 4500, 'service', 'NGN'),
  ('Bottled water (case of 50)', 5000, 'sale', 'NGN'),
  ('Deep home cleaning (3-bedroom)', 45000, 'service', 'NGN'),
  ('Backpack', 15000, 'sale', 'NGN'),
  ('Generator servicing', 18000, 'service', 'NGN'),
  ('Ankara fabric (per yard)', 4500, 'sale', 'NGN'),
  ('Vegetable oil (5L)', 12500, 'sale', 'NGN'),
  ('Dry cleaning (suit)', 6500, 'service', 'NGN'),
  ('Fumigation service', 25000, 'service', 'NGN'),
  ('Detergent powder (1kg)', 1800, 'sale', 'NGN'),
  ('Printer paper (ream)', 3800, 'sale', 'NGN'),
  ('Business consulting (per hour)', 20000, 'service', 'NGN'),
  ('Insecticide spray', 2400, 'sale', 'NGN'),
  ('Graphic design service', 20000, 'service', 'NGN'),
  ('Photography session (1 hour)', 25000, 'service', 'NGN'),
  ('Sprite (crate of 24)', 4800, 'sale', 'NGN'),
  ('Paint (4L, emulsion)', 9500, 'sale', 'NGN'),
  ('Rechargeable lantern', 8500, 'sale', 'NGN'),
  ('Hair braiding (full head)', 15000, 'service', 'NGN'),
  ('HDMI cable (2m)', 3200, 'sale', 'NGN'),
  ('Memory card (64GB)', 11000, 'sale', 'NGN'),
  ('Personal training session', 15000, 'service', 'NGN'),
  ('Chair and canopy rental (100 seats)', 60000, 'service', 'NGN'),
  ('Accounting/bookkeeping (monthly)', 35000, 'service', 'NGN'),
  ('Phone battery replacement', 8000, 'service', 'NGN'),
  ('Bar soap (pack of 6)', 1500, 'sale', 'NGN'),
  ('Men''s cap', 2500, 'sale', 'NGN'),
  ('Bottled water (case of 24)', 3500, 'sale', 'NGN'),
  ('Pedicure', 5500, 'service', 'NGN'),
  ('Ironing service (per item)', 500, 'service', 'NGN'),
  ('Cement (1 bag)', 8500, 'sale', 'NGN'),
  ('Handbag', 18500, 'sale', 'NGN'),
  ('Eggs (crate of 30)', 3200, 'sale', 'NGN'),
  ('Tea bags (box of 100)', 2200, 'sale', 'NGN'),
  ('Memory card (32GB)', 6500, 'sale', 'NGN'),
  ('Matches (pack of 10 boxes)', 500, 'sale', 'NGN'),
  ('Men''s belt (leather)', 6000, 'sale', 'NGN'),
  ('Rice (50kg bag)', 65000, 'sale', 'NGN'),
  ('Home cleaning service (per room)', 8000, 'service', 'NGN'),
  ('Men''s t-shirt', 5500, 'sale', 'NGN'),
  ('Umbrella', 3500, 'sale', 'NGN'),
  ('USB cable (1m)', 1500, 'sale', 'NGN'),
  ('Data recovery service', 20000, 'service', 'NGN'),
  ('Courier/delivery (within city)', 2000, 'service', 'NGN'),
  ('Legal consultation (per hour)', 15000, 'service', 'NGN'),
  ('Women''s hair styling', 8500, 'service', 'NGN'),
  ('Phone charger (Type-C)', 3500, 'sale', 'NGN'),
  ('Social media management (monthly)', 60000, 'service', 'NGN'),
  ('Coca-Cola (crate of 24)', 4800, 'sale', 'NGN'),
  ('Car wash (full detailing)', 15000, 'service', 'NGN'),
  ('Phone screen repair', 15000, 'service', 'NGN'),
  ('Phone screen protector', 1500, 'sale', 'NGN'),
  ('Full body massage', 25000, 'service', 'NGN'),
  ('Candles (pack of 12)', 1600, 'sale', 'NGN'),
  ('Laundry service (per load)', 3500, 'service', 'NGN'),
  ('Ballpoint pens (pack of 10)', 1200, 'sale', 'NGN'),
  ('Men''s haircut', 2500, 'service', 'NGN'),
  ('Phone charger (Lightning)', 4200, 'sale', 'NGN'),
  ('Phone case', 3000, 'sale', 'NGN'),
  ('Coffee (250g)', 3800, 'sale', 'NGN'),
  ('Laptop repair (motherboard)', 45000, 'service', 'NGN'),
  ('Spaghetti (carton)', 8500, 'sale', 'NGN'),
  ('Malt drink (crate of 24)', 6500, 'sale', 'NGN'),
  ('Bridal makeup package', 45000, 'service', 'NGN'),
  ('Bread (loaf)', 1200, 'sale', 'NGN'),
  ('Passport photo session', 1500, 'service', 'NGN'),
  ('Women''s blouse', 7500, 'sale', 'NGN'),
  ('Electrical wiring repair', 15000, 'service', 'NGN'),
  ('Car wash (exterior)', 3000, 'service', 'NGN'),
  ('Facial treatment', 12000, 'service', 'NGN'),
  ('Tailoring (suit)', 35000, 'service', 'NGN'),
  ('Plumbing repair (per visit)', 12000, 'service', 'NGN');
